export const countries = [
  { id: "US", label: "United States" },
  { id: "CA", label: "Canada" },
  { id: "GB", label: "United Kingdom" },
  { id: "AU", label: "Australia" },
  { id: "NZ", label: "New Zealand" },
  { id: "IE", label: "Ireland" },
  { id: "DE", label: "Germany" },
  { id: "FR", label: "France" },
  { id: "ES", label: "Spain" },
  { id: "IT", label: "Italy" },
  { id: "NL", label: "Netherlands" },
  { id: "BE", label: "Belgium" },
  { id: "CH", label: "Switzerland" },
  { id: "AT", label: "Austria" },
  { id: "DK", label: "Denmark" },
  { id: "SE", label: "Sweden" },
  { id: "NO", label: "Norway" },
  { id: "FI", label: "Finland" },
  { id: "PL", label: "Poland" },
  { id: "CZ", label: "Czech Republic" },
  { id: "PT", label: "Portugal" },
  { id: "GR", label: "Greece" },
  { id: "JP", label: "Japan" },
  { id: "KR", label: "South Korea" },
  { id: "SG", label: "Singapore" },
  { id: "HK", label: "Hong Kong" },
  { id: "IN", label: "India" },
  { id: "MX", label: "Mexico" },
  { id: "BR", label: "Brazil" },
  { id: "AR", label: "Argentina" },
  { id: "CL", label: "Chile" },
  { id: "ZA", label: "South Africa" },
  { id: "AE", label: "United Arab Emirates" },
  { id: "SA", label: "Saudi Arabia" },
  { id: "IL", label: "Israel" },
  { id: "TR", label: "Turkey" },
  { id: "RU", label: "Russia" },
  { id: "CN", label: "China" },
  { id: "TH", label: "Thailand" },
  { id: "MY", label: "Malaysia" },
  { id: "ID", label: "Indonesia" },
  { id: "PH", label: "Philippines" },
  { id: "VN", label: "Vietnam" },
  { id: "EG", label: "Egypt" },
  { id: "NG", label: "Nigeria" },
  { id: "KE", label: "Kenya" },
];
